title: Choosing random items from a list in Python
hero_image: images/banner.png
description: Picking random items from a list in Python
original_url: 
theme: cc-prototype
listed: false
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - title: Picking random items
